### ISSUE TITLE
Implement a data validation after uploading

### ISSUE THREAD

**Issue by tiwalter** [Traeger-GmbH/release-server#15]
Validation criteria:
- Data <=500 MB
- Zip contains all needed elements (contained in deployment.json)
- Deployment.Json as expected

**Comment by f-porter** [comment]
Please do not miss to check if the payload actually is a valid .zip file as the request would result in an `Internal Server Error` otherwise.

**Comment by tiwalter** [comment]
will be realized with the issue #14
