### ISSUE TITLE
Use ContentDispositionHeaderValue

### ISSUE THREAD

**Issue by f-porter** [Traeger-GmbH/release-server#27]
The current implementation uses __System.Net.Mime.ContentDisposition__ for setting the content disposition header value:
https://github.com/Traeger-GmbH/release-server/blob/8a936682dcfac18c0b97c3085779d57c699c8f54/Sources/ReleaseServer/ReleaseServer.WebApi/Controllers/ReleaseArtifactController.cs#L88
@kpreisser pointed out that this class is meant for usage in email headers and can result in incorrect header values depending of the filename's length and characters.
To ensure a correct header value we should use __System.Net.Http.Headers.ContentDispositionHeaderValue__ for this purpose:

```csharp
var cd = new ContentDispositionHeaderValue("attachment")
{
    FileNameStar = response.Filename;
}
```

**Comment by tiwalter** [comment]
Now, the correct ContentDispositionHeaderValue is used
