### ISSUE TITLE
Adjust the retrieved product information 

### ISSUE THREAD

**Issue by tiwalter** [Traeger-GmbH/release-server#32]
If you request the informations of a certain product, it has to be look like the following example:

````json
{
        "Identifier": "productx",
        "Version": "1.0",
        "OS": "debian",
        "Architecture": "amd64"
 }
````

**Comment by f-porter** [comment]
We would prefer camel case naming of the properties. So the object should look like this:

```
{
  "identifier": "productx",
  "version": "1.0",
  "os": "debian",
  "architecture": "amd64"
 }
```

This can be configured in the class __Startup__ in the method __ConfigureServices()__ like this:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers()
            .AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            })

    services.AddAuthentication("BasicAuthentication")
            .AddScheme<AuthenticationSchemeOptions, BasicAuthHandler>("BasicAuthentication", null);
}
```

**Comment by tiwalter** [comment]
@f-porter the JsonSerializerOptions in the ConfigureServices() only works, if we use MVC.

I solved the camel case issue with a JsonSerializer of System.Text.Json incl. the camel case serialzer setting:

Here the options: 
`JsonSerializerOptions = new JsonSerializerOptions {PropertyNamingPolicy = JsonNamingPolicy.CamelCase};`

Here the usage of the JsonSerializer:
`  JsonSerializer.Serialize(FsReleaseArtifactService.GetProductInfos(product),JsonSerializerOptions);`

Also see: 
https://github.com/Traeger-GmbH/release-server/blob/master/Sources/ReleaseServer/ReleaseServer.WebApi/Controllers/ReleaseArtifactController.cs#L25
