### ISSUE TITLE
Compare passwords in constant time to avoid timing attack vulnerabilities

### ISSUE THREAD

**Issue by kpreisser** [Traeger-GmbH/release-server#33]
I noticed `BasicAuthHandler` does a string comparison on the user's password:
https://github.com/Traeger-GmbH/release-server/blob/1313db1a372ef7f880665f212a8aaee40b063552/Sources/ReleaseServer/ReleaseServer.WebApi/Handlers/BasicAuthHandler.cs#L80-L91

Comparing passwords using a simple `string.Equals` can make the code vulnerable to [timing attacks](https://en.wikipedia.org/wiki/Timing_attack), as a simple equals method will return as early as possible (when it finds the first mismatch). 

Instead, for comparing passwords or other secret information, a method like [`CryptographicOperations.FixedTimeEquals`](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.cryptographicoperations.fixedtimeequals?view=netcore-3.0#System_Security_Cryptography_CryptographicOperations_FixedTimeEquals_System_ReadOnlySpan_System_Byte__System_ReadOnlySpan_System_Byte__) should be used that compares the sequences in constant time.

Additionally, I think `Encoding.Default` should not be used anymore, as it depends on the OS. E.g. on Windows, it returns the language/region-specific ANSI encoding (e.g. `Windows-1252` on german systems, `gb2312` on chinese (simplified) systems).
Instead, it should probably be `Encoding.UTF8` or `Encoding.Unicode`.

Thanks!

**Comment by tiwalter** [comment]
The fix is implemented now.
