### ISSUE TITLE
Docker image: The framework 'Microsoft.AspNetCor.App', version '3.1.0' was not found

### ISSUE THREAD

**Issue by f-porter** [Traeger-GmbH/release-server#38]
Running the latest image __traeger/release-server:latest__ results in the following output:

```
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=debian.10-x64
```

It seems that the current runner image does not provide the AspNetCore framework:
https://github.com/Traeger-GmbH/release-server/blob/3a3091018b59935eddf70521df81c598fe5ec090/Dockerfile#L14

Maybe this can be fixed by using the official AspNetCore runtime image __mcr.microsoft.com/dotnet/core/aspnet__

**Comment by tiwalter** [comment]
Fixed the runtime
