### ISSUE TITLE
Enable debugging independent of environment

### ISSUE THREAD

**Issue by f-porter** [Traeger-GmbH/release-server#39]
Currently the server expects an environment variable __SERVER_AUTH_PATH__ that contains the path of the file __credentials.json__.
This way one has to somehow set this environment variable and create a file that contains the expected data before being able to just debug/run the program.

Anyone should be able to simply debug/run the program without the need of setting up any environment:

1. Clone the repository
2. cd into the application directory release-server/Sources/ReleaseServer/ReleaseServer.WebApi
3. dotnet run ReleaseServer.WebApi.csproj

This could be achieved by adding some kind of default mechanism that does not require any additional setup. The expected file could be added to the repository.

However is it necessary to have a separate file __credentials.json__?
Why not just setting the credentials in __appsettings.json__?

**Comment by tiwalter** [comment]
As discussed with @f-porter i eliminated the credentials.json and moved the content to appsettings.json.

The appsettings.Development.json has now a default user.
