### ISSUE TITLE
Use separate files for each component

### ISSUE THREAD

**Issue by f-porter** [Traeger-GmbH/release-server#48]
To meet our coding guidelines each component has to be located in a separate file whose filename matches the name of the respective component.
This structure improves the comprehensibility of the project.

For example currently the class `FsReleaseArtifactRepository` and the interface `IReleaseArtifactRepository` are both contained in the file `ReleaseArtifactRepository.cs`.
These shall be separated:
* `FsReleaseArtifactRepository` in a file named `FsReleaseArtifactRepository.cs`
* `IReleaseArtifactRepository` in a file named `IReleaseArtifactRepository.cs`

**Comment by tiwalter** [comment]
Fixed by #52
